<?php
/**
 * CategoryId
 *
 * PHP version 8.1
 *
 * @package  Aternos\PoggitApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Poggit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aternos\PoggitApi\Model;

/**
 * CategoryId Class Doc Comment
 *
 * @package  Aternos\PoggitApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum CategoryId: int
{
    case GENERAL = 1;

    case ADMIN_TOOLS = 2;

    case INFORMATIONAL = 3;

    case ANTI_GRIEFING_TOOLS = 4;

    case CHAT_RELATED = 5;

    case TELEPORTATION = 6;

    case MECHANICS = 7;

    case ECONOMY = 8;

    case MINIGAME = 9;

    case FUN = 10;

    case WORLD_EDITING_AND_MANAGEMENT = 11;

    case WORLD_GENERATORS = 12;

    case DEVELOPER_TOOLS = 13;

    case EDUCATIONAL = 14;

    case MISCELLANEOUS = 15;

    case API_PLUGINS = 16;

    case VANILLA_MECHANICS = 17;
}


