<?php
/**
 * CategoryName
 *
 * PHP version 8.1
 *
 * @package  Aternos\PoggitApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Poggit API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aternos\PoggitApi\Model;

/**
 * CategoryName Class Doc Comment
 *
 * @package  Aternos\PoggitApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum CategoryName: string
{
    case GENERAL = 'General';

    case ADMIN_TOOLS = 'Admin Tools';

    case INFORMATIONAL = 'Informational';

    case ANTI_GRIEFING_TOOLS = 'Anti-Griefing Tools';

    case CHAT_RELATED = 'Chat-Related';

    case TELEPORTATION = 'Teleportation';

    case MECHANICS = 'Mechanics';

    case ECONOMY = 'Economy';

    case MINIGAME = 'Minigame';

    case FUN = 'Fun';

    case WORLD_EDITING_AND_MANAGEMENT = 'World Editing and Management';

    case WORLD_GENERATORS = 'World Generators';

    case DEVELOPER_TOOLS = 'Developer Tools';

    case EDUCATIONAL = 'Educational';

    case MISCELLANEOUS = 'Miscellaneous';

    case API_PLUGINS = 'API plugins';

    case VANILLA_MECHANICS = 'Vanilla Mechanics';
}


